ensemble01site_homepage:
    path:     /
    defaults: { _controller: ensemble01siteBundle:site:index }

ensemble01site_pageweb:
    path:     /page-web/{page}/{dossier}
    defaults: { _controller: ensemble01siteBundle:site:pageweb, page: 'homepage', dossier: null }


# GÉNÉRATION DES RAPPORTS PAR URL PUBLIQUE

ensemble01site_rapportfm:
    path:     /rapportfm/{id}/{mode}.{format}/{pagedata}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_rapport, id: null, mode: "file", format: "pdf", pagedata: null}

# génération d'un rapport individuel via FM
ensemble01filemake_generateByOne:
    path:     /rapportfm-by-one/{numlot}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_rappport_fm}

ensemble01filemaker_generateByLotRapport:
    path:     /rapportfm-by-lot/{numlot}/{pagedata}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_by_lot_rapport, pagedata: null}

## url pour lancer des rapports par numéro de lot via FM
ensemble01filemaker_commandeFM_generateByLotRapport:
    path:     /rapportfm-by-lot-action-fm/{numlot}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_by_lot_rapport_fm}

ensemble01filemaker_public_listeRapportsLots:
    path:     /liste-rapports-lot/{numlot}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:public_listeRapportsLots, numlot: null}

### STATESAVE DATATABLES ###
datatables_statesave:
    path:     /datatables/statesave
    defaults: { _controller: ensemble01filemakerBundle:filemaker:datatables_statesave }

### TEST FM
ensemble01filemaker_test_refresh:
    path:     /test/refresh
    defaults: { _controller: ensemble01filemakerBundle:filemaker:test_refresh}
