ensemble01site_homepage:
    path:     /
    defaults: { _controller: ensemble01siteBundle:site:index }

ensemble01site_pageweb:
    path:     /page-web/{page}/{dossier}
    defaults: { _controller: ensemble01siteBundle:site:pageweb, page: 'homepage', dossier: null }


# GÉNÉRATION DES RAPPORTS PAR URL PUBLIQUE

ensemble01site_rapportfm:
    path:     /rapportfm/{id}/{mode}.{format}/{pagedata}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_rapport, id: null, mode: "file", format: "pdf", pagedata: null}

    # Rapport PDF ajax
ensemble01site_rapportPDFrefresh:
    path:     /rapportpdfrefresh/{id}/{pagedata}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_ajax_pdf_rapport, pagedata: null}

ensemble01site_rapportsload:
    path:     /rapport-pdf-load/{id}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:file_pdf_rapport}

ensemble01site_rapportscreen:
    path:     /rapport-pdf-screen/{id}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:screen_pdf_rapport}

# génération d'un rapport individuel via FM
## --> lancé par FM pour générer les lots de rapports
ensemble01filemake_generateByOne:
    path:     /rapportfm-by-one/{rapport_id}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_rapport_fm}

# rétablissement d'un rapport individuel via FM
ensemble01filemake_RetablishByOne:
    path:     /rapportfm-retablish-one/{rapport_id}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:retablish_rapport_fm}

ensemble01filemaker_generateByLotRapport:
    path:     /rapportfm-by-lot/{numlot}/{pagedata}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_by_lot_rapport, pagedata: null}

## url pour lancer des rapports par numéro de lot via FM
ensemble01filemaker_commandeFM_generateByLotRapport:
    path:     /rapportfm-by-lot-action-fm/{numlot}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_by_lot_rapport_fm}

## --> visualiseur en live
ensemble01filemaker_public_listeRapportsLots:
    path:     /live-rapports-lot/{numlot}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:public_listeRapportsLots, numlot: null}

## --> téléchargement ZIP
ensemble01filemaker_ZIP_listeRapportsLots:
    path:     /zip-rapports-lot/{numlot}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:ZIP_listeRapportsLots}

ensemble01filemaker_check_listeRapportsLots:
    path:     /check-rapports-lot/{numlot}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:check_listeRapportsLots}

### STATESAVE DATATABLES ###
datatables_statesave:
    path:     /datatables/statesave
    defaults: { _controller: ensemble01filemakerBundle:filemaker:datatables_statesave }

### TEST FM
ensemble01filemaker_test_refresh:
    path:     /test/refresh
    defaults: { _controller: ensemble01filemakerBundle:filemaker:test_refresh}
