ensemble01filemaker_homepage:
    path:     /
    defaults: { _controller: ensemble01filemakerBundle:filemaker:index }

ensemble01filemaker_pageweb:
    path:     /page-web/{page}/{dossier}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:pageweb, page: 'homepage', dossier: null }

ensemble01filemaker_generateRapport:
    path:     /rapport/{id}/{type}/{mode}-{format}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_rapport, mode: "view", format: "pdf", type: "RDM-DAPP"}