### PAGES ###

ensemble01filemaker_homepage:
    path:     /
    defaults: { _controller: ensemble01filemakerBundle:filemaker:index }

ensemble01filemaker_pageweb:
    path:     /page-web/{page}/{pagedata}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:pageweb, page: 'homepage', pagedata: null }


### MANIPULATION DES DONNÉES FM ###

ensemble01filemaker_changeserver:
    path:     /change-fm-server/{servernom}/{page}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:changeserver, page: 'homepage' }

ensemble01filemaker_changebase:
    path:     /change-fm-base/{basenom}/{page}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:changebase, page: 'homepage' }


### GÉNÉRATION DES RAPPORTS ###

ensemble01filemaker_generateRapport:
    path:     /rapport/{id}/{mode}.{format}/{pagedata}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:generate_rapport, mode: "file", format: "pdf", pagedata: null}

ensemble01filemaker_traiteRapports:
    path:     /traitement-rapports
    defaults: { _controller: ensemble01filemakerBundle:filemaker:traitement_rapports }


### FONCTIONNALITÉS DEV / SADMIN

ensemble01filemaker_retablirByLotRapport:
    path:     /s-admin/retablir-rapportfm-by-lot/{numlot}/{pagedata}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:retablir_by_lot_rapport, pagedata: null}
