ensemble01filemaker_homepage:
    path:     /
    defaults: { _controller: ensemble01filemakerBundle:filemaker:index }

ensemble01filemaker_pageweb:
    path:     /page-web/{page}/{dossier}
    defaults: { _controller: ensemble01filemakerBundle:filemaker:pageweb, page: 'homepage', dossier: null }

ensemble01filemaker_PDFgenerateRapport:
    path:     /pdf/rapport/{type}-{id}/test.pdf
    defaults: { _controller: ensemble01filemakerBundle:filemaker:PDF_generate_rapport}