services:
#    ensemble01filemaker.example:
#        class: ensemble01\filemakerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # Fonctionnalités de requêtes et dossiers/fichiers
    ensemble01services.aetools:
        class: ensemble01\services\aetools
        arguments: [@service_container]

    ensemble01services.geodiag:
        class: ensemble01\services\geodiag
        arguments: [@service_container]

    ensemble01services.selection:
        class: ensemble01\services\aeSelect
        arguments: [@service_container]

    # ensemble01services.geodiagmin:
    #     class: ensemble01\services\geodiagmin
    #     arguments: [@service_container]

    ###################################
    ### EVENT LISTENER AU DÉMARRAGE DE REQUETE PRINCIPALE
    ###################################

    # EventListerner sur paramètres généraux du site
    ensemble01.site_listener:
        class: ensemble01\services\geodiag
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: load_fmservice }

